feat: add modal info and change layout
kodepintar/colorful-quran pull request #61
Opened 2021-11-05 09:54 UTC by sangvictim

still not finish

2021-11-05 11:28 UTC, axmad386 requested changes
Cuman standarisasi

2021-11-05 11:28 UTC, axmad386 commented on src/component/Modal.svelte
> +	export let Title:string;
Dibikin cameCase aja gmn gan?
Props atau varibel lebih baik camelCase
Misal surahDetail, title, subTitle
Kalau PascalCase biasnya buat penamaan class atau component misa TajweedView

2021-11-06 10:02 UTC, sangvictim commented on src/component/Modal.svelte
> +	export let Title:string;
ok tak revisi

2021-11-06 13:26 UTC, axmad386 commented on .chglog/CHANGELOG.tpl.md
>  {{ if .Versions -}}
iki file keupdate formatermu?
tak revert ya

2021-11-06 16:48 UTC, axmad386 commented on .chglog/CHANGELOG.tpl.md
>  {{ if .Versions -}}
done

2021-11-06 16:52 UTC, axmad386 approved these changes
OK

2021-11-06 16:52 UTC, axmad386 commented
thanks @sangvictim

2021-11-06 16:54 UTC, merged